version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies 
          command: |
            apk add --update make wget
      - run:
          name: Building Docker container
          no_output_timeout: 1h
          command: |
              export DOCKER_NAME=$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:latest
              docker build -t $DOCKER_NAME .
              docker save $DOCKER_NAME -o /tmp/docker_image.tar
      - persist_to_workspace:
          root: /tmp
          paths:
            - docker_image.tar

  test:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - setup_remote_docker            
      - attach_workspace:
          at: /tmp/workspace
      - run: 
          name: Load docker image
          command: |
            docker load -i /tmp/workspace/docker_image.tar
      - run:
          name: Running Tests
          command: |
              export DOCKER_NAME=$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:latest
              # put tests here
              docker run -it $DOCKER_NAME ls

  deploy:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - setup_remote_docker            
      - attach_workspace:
          at: /tmp/workspace
      - run: 
          name: Load docker image
          command: |
            docker load -i /tmp/workspace/docker_image.tar
      - run:
          name: Pushing build to docker hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            export DOCKER_NAME=$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:latest
            # tag and push here:
            echo docker push $DOCKER_NAME
            docker push $DOCKER_NAME

  deploy_shub:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker            
      - run:
          name: Pushing latest to singularity hub 
          command: |
            export DOCKER_NAME=$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:latest
            git config --global user.email $GH_EMAIL
            git config --global user.name $GH_NAME
            echo "Bootstrap: docker" > Singularity
            echo "From: $DOCKER_NAME" >> Singularity
            git add Singularity
            git commit -m "shub build latest [skip ci]"
            git push -q https://${GITHUB_TOKEN}@github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME.git

      - run:
          name: Pushing build to docker hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            export DOCKER_NAME=$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:latest
            # tag and push here:
            echo docker push $DOCKER_NAME
            docker push $DOCKER_NAME



#uncomment below for shub build
#      - run:
#          name: Pushing latest to singularity hub test
#          command: |
#            git config --global user.email $GH_EMAIL
#            git config --global user.name $GH_NAME
#            echo "" >> Singularity
#            git add Singularity
#            git commit -m "shub build latest [skip ci]"
#            git push -q https://${GITHUB_TOKEN}@github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME.git

workflows:
  version: 2
  dev_commit:
    jobs: 
      - build:
          context: org-global
      - test:
          requires:
            - build
          context: org-global
      - deploy:
          requires:
            - build
            - test
          context: org-global
      - deploy_shub:
          requires:
            - build
            - test
            - deploy
          context: org-global
