version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    environment:
      VERSION: v1.4
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies 
          command: |
            apk add --update make wget
      - run:
          name: Building Docker container
          no_output_timeout: 1h
          command: |
              export DOCKER_NAME=$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$VERSION.$CIRCLE_BUILD_NUM
              # put build command here:
              echo docker build -t $DOCKER_NAME .
              echo docker save $DOCKER_NAME -o /tmp/docker_image.tar > /tmp/docker_image.tar
      - persist_to_workspace:
          root: /tmp
          paths:
            - docker_image.tar
      - run:
          name: Running Tests
          command: |
              export DOCKER_NAME=$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$VERSION.$CIRCLE_BUILD_NUM
              # put tests here
              echo docker run -it $DOCKER_NAME flirt -version
      - run:
          name: Pushing build to docker hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            export DOCKER_NAME=$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$VERSION.$CIRCLE_BUILD_NUM
            export DOCKER_LATEST=$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:latest
            # tag and push here:
            echo docker tag $DOCKER_NAME $DOCKER_LATEST
            echo docker push $DOCKER_LATEST
            echo docker push $DOCKER_NAME
  test:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker            
      - attach_workspace:
          at: /tmp/workspace
      - run: 
          name: Load docker image
          command: |
            ls /tmp/workspace
            #           cat /tmp/workspace/docker_image.tar

#uncomment below for shub build
#      - run:
#          name: Pushing latest to singularity hub test
#          command: |
#            git config --global user.email $GH_EMAIL
#            git config --global user.name $GH_NAME
#            echo "" >> Singularity
#            git add Singularity
#            git commit -m "shub build latest [skip ci]"
#            git push -q https://${GITHUB_TOKEN}@github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME.git

workflows:
  version: 2
  build_and_test:
    jobs: 
      - build:
          context: org-global
      - test:
          context: org-global
          
